import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import background from "../public/img/16150@3x.png"
import logo from "../public/img/pakan-logo-types-01@3x.png"
import Call from "../public/img/call-center-g@3x.png"
import Time from "../public/img/time-g@3x.png"
import Pin from "../public/img/location.png"
import MyLoc from "../public/img/gps.png"
import MainBackground from "../public/img/mask-group-1@3x.png"






const YekanBakh = localFont({
  src: "./fonts/YekanBakh-Regular.ttf",
  variable: "--font-yekanBakh",
  weight: "100 900",
});
const YekanBakhMono = localFont({
  src: "./fonts/YekanBakh-Bold.woff",
  variable: "--font-YekanBakh-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div dir="rtl"
        className={`${styles.page} ${YekanBakh.variable} ${YekanBakhMono.variable}`}
      >
        <header className={styles.header}>
          <div className={styles.headerNav}>
            <div dir="ltr" className={styles.headerInfo}>

            <span className={styles.callNumber}>
            <Image
              className={styles.call}
              src={Call}
              alt="Call"
              width={20}
              height={20}
              priority
            /> 
            021-41774
            <div className={styles.lineFirst}></div>
            </span>
            <span>
            <Image
              className={styles.Time}
              src={Time}
              alt="Time"
              width={20}
              height={20}
              priority
            />
              روز های کاری 8:00 تا 18:30 | جمعه ها 9:00 تا 17:00
               
            </span>
            <div className={styles.lineFirst}></div>
          </div>
          <div className={styles.line}></div>
          <div className={styles.Navbar}>
           <span className={styles.NavbarFirst}>
              <Image
                className={styles.logo}
                src={logo}
                alt="logo"
                width={55}
                height={55}
                priority
              /> 
              <i>درباره ما</i>
              <i>خدمات</i> 
              <i>خدمات سازمانی</i> 
              <i>نحوه درخواست</i> 
              <i>تماس با ما</i> 
              <i> ویترین</i>
              <i> بلاگ</i>  
            </span>
            <span className={styles.NavbarSecond}> 
              <a href="#">ثبت نام</a> 
              <button>ورود</button> 
            </span> 
          </div>   
        
          </div>
         
          
          <div><Image
              className={styles.headerBack}
              src={background}
              alt="background"
              priority
            /> 
             <span className={styles.title}>خونه تکونی همراه شماییم</span>
             <span className={styles.description}>باز و نصب و شستن پرده‌ها باما</span>
          </div>
          <div className={styles.headerLoc}>
            <Image className={styles.pin}
             src={Pin}
             alt="Pin"
             priority
            
           /> 
           <div className={styles.address}>
              <p className={styles.addressText}>محله سعادت آباد - ویرایش</p>
              <span className={styles.addressLine}></span>
           </div>
           <div className={styles.MyLoction}>
              <Image className={styles.MyLoc}
                src={MyLoc}
                alt="MyLoc"
                priority
            
              /> 
           </div>
           <button className={styles.findLoc} >بررسی محدوده و درخواست سرویس</button>
            
          </div>
          <Image className={styles.MainBackground}
                src={MainBackground}
                alt="MainBackground"
                priority
              /> 
        </header>

        <main className={styles.main}>
          <div>
          
          </div>
         
          
            
      
         
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
